name: VServer SSH Stats
version: "1.2.3"
slug: vserver_ssh_stats
description: Holt CPU, RAM, Disk, Net per SSH (ohne Agent) und veröffentlicht sie via MQTT.
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:server
panel_title: VServer SSH Stats
panel_admin: false
init: false
arch:
  - amd64
  - armv7
  - aarch64
options:
  mqtt_host: homeassistant
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  interval_seconds: 30
  disabled_entities: []
  servers:
    - name: "vps1"
      host: "203.0.113.10"
      username: "root"
      password: "deinpasswort"
      # alternatively: key: "/path/to/id_rsa"
      # optional: port: 22
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  interval_seconds: int
  disabled_entities:
    - match(cpu|mem|disk|net_in|net_out|uptime|temp|ram|cores|load_1|load_5|load_15|cpu_freq|os|pkg_count|pkg_list)
  servers:
    - name: str
      host: str
      username: str
      password: str?
      key: str?
      port: int?
