#!/usr/bin/env python3
"""Generate a least-privilege sudoers snippet for a VServer SSH Stats monitoring user.

The generated rules only cover the exact command forms the integration invokes
(see custom_components/vserver_ssh_stats/__init__.py and remote_collector.sh).
Review the output, adjust binary paths for your distribution (`which <tool>`),
and validate the file with `visudo -c -f <file>` before installing it.
"""
from __future__ import annotations

import argparse
import sys

PACKAGE_MANAGER_RULES = {
    "apt": [
        "/usr/bin/apt-get update",
        "/usr/bin/apt-get -y upgrade",
        "/usr/bin/apt-get clean",
    ],
    "dnf": [
        "/usr/bin/dnf -y upgrade",
        "/usr/bin/dnf -y makecache",
        "/usr/bin/dnf clean all",
    ],
    "yum": [
        "/usr/bin/yum -y update",
        "/usr/bin/yum -y makecache",
        "/usr/bin/yum clean all",
    ],
    "pacman": [
        "/usr/bin/pacman -Sy --noconfirm",
        "/usr/bin/pacman -Sc --noconfirm",
    ],
    "zypper": [
        "/usr/bin/zypper --non-interactive refresh",
        "/usr/bin/zypper clean --all",
    ],
    "apk": [
        "/sbin/apk update",
        "/sbin/apk cache clean",
    ],
}

REBOOT_RULES = ["/sbin/reboot"]

DOCKER_RULES = ["/usr/bin/docker *"]

STORAGE_HEALTH_RULES = [
    "/usr/sbin/smartctl -a /dev/*",
    "/usr/sbin/nvme smart-log /dev/*",
    "/usr/sbin/mdadm --detail --export /dev/md*",
]

FIREWALL_STATUS_RULES = [
    "/usr/sbin/ufw status verbose",
    "/usr/sbin/nft -a list ruleset",
    "/usr/sbin/iptables -S",
]

JOURNAL_READ_RULES = [
    "/usr/bin/journalctl -u * -n * --no-pager",
    "/usr/bin/journalctl -n * --no-pager",
]

FAIL2BAN_STATUS_RULES = [
    "/usr/bin/fail2ban-client status",
    "/usr/bin/fail2ban-client status *",
]


def build_rules(args: argparse.Namespace) -> list[str]:
    """Return the fully qualified sudoers command lines for the selected features."""

    rules: list[str] = []

    if args.package_manager:
        rules.extend(PACKAGE_MANAGER_RULES[args.package_manager])

    if args.reboot:
        rules.extend(REBOOT_RULES)

    if args.docker:
        rules.extend(DOCKER_RULES)

    for service in args.service:
        rules.append(f"/usr/bin/systemctl restart {service}")

    if args.storage_health:
        rules.extend(STORAGE_HEALTH_RULES)

    if args.firewall_status:
        rules.extend(FIREWALL_STATUS_RULES)

    if args.journal_read:
        rules.extend(JOURNAL_READ_RULES)

    if args.fail2ban:
        rules.extend(FAIL2BAN_STATUS_RULES)

    return rules


def render_sudoers(user: str, rules: list[str]) -> str:
    """Render a NOPASSWD sudoers snippet for *user* covering *rules*."""

    lines = [
        "# Generated by scripts/generate_sudoers_template.py",
        "# Review every path below with `which <tool>` on the target host before installing.",
        "# Install with: visudo -c -f <file> && cp <file> /etc/sudoers.d/vserver-ssh-stats",
        f"Defaults:{user} !requiretty",
    ]
    for rule in rules:
        lines.append(f"{user} ALL=(root) NOPASSWD: {rule}")
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--user",
        required=True,
        help="Name of the dedicated SSH monitoring user on the target host.",
    )
    parser.add_argument(
        "--package-manager",
        choices=sorted(PACKAGE_MANAGER_RULES),
        help="Include package update/upgrade/cache-clean rules for one package manager.",
    )
    parser.add_argument(
        "--reboot",
        action="store_true",
        help="Allow the reboot_host action.",
    )
    parser.add_argument(
        "--docker",
        action="store_true",
        help="Allow `sudo docker ...` as a fallback when the user is not in the docker group. "
        "Prefer adding the user to the docker group instead; this is root-equivalent.",
    )
    parser.add_argument(
        "--service",
        action="append",
        default=[],
        metavar="NAME",
        help="Allow restarting one systemd service by name. Repeat for multiple services.",
    )
    parser.add_argument(
        "--storage-health",
        action="store_true",
        help="Allow the read-only SMART/NVMe/mdadm storage-health fallback commands.",
    )
    parser.add_argument(
        "--firewall-status",
        action="store_true",
        help="Allow the read-only ufw/nftables/iptables firewall-status fallback commands.",
    )
    parser.add_argument(
        "--journal-read",
        action="store_true",
        help="Allow reading systemd journal logs via `sudo journalctl`.",
    )
    parser.add_argument(
        "--fail2ban",
        action="store_true",
        help="Allow the read-only `fail2ban-client status[/status <jail>]` fallback commands.",
    )
    parser.add_argument(
        "--output",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="Write the sudoers snippet to this file instead of stdout.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    rules = build_rules(args)
    if not rules:
        print(
            "No features selected; nothing to generate. "
            "Pass at least one of --package-manager/--reboot/--docker/--service/"
            "--storage-health/--firewall-status/--journal-read/--fail2ban.",
            file=sys.stderr,
        )
        return 1
    args.output.write(render_sudoers(args.user, rules))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
