name: Auto Version Bump

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Bump version
        run: |
          python scripts/bump_version.py
          if git diff --quiet; then
            echo "Version unchanged"
          else
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -am 'chore: bump version'
            git push
          fi
